// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWkFQhv91Om49zz2BZcllieXPIUZZuHc',
    appId: '1:860783457646:web:25d230c35dbc1e1836bd7f',
    messagingSenderId: '860783457646',
    projectId: 'pls-app-server',
    authDomain: 'pls-app-server.firebaseapp.com',
    storageBucket: 'pls-app-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82AGTihEbG6-cYu8bVJoNFcfCaF-afKY',
    appId: '1:860783457646:android:25d09afe5a28e0ad36bd7f',
    messagingSenderId: '860783457646',
    projectId: 'pls-app-server',
    storageBucket: 'pls-app-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWdPau3HHffJauBqheM1Aw5PSDEWUF8gA',
    appId: '1:860783457646:ios:ad4eeefb00dc783836bd7f',
    messagingSenderId: '860783457646',
    projectId: 'pls-app-server',
    storageBucket: 'pls-app-server.appspot.com',
    iosBundleId: 'com.example.promiseSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWdPau3HHffJauBqheM1Aw5PSDEWUF8gA',
    appId: '1:860783457646:ios:ad4eeefb00dc783836bd7f',
    messagingSenderId: '860783457646',
    projectId: 'pls-app-server',
    storageBucket: 'pls-app-server.appspot.com',
    iosBundleId: 'com.example.promiseSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYWkFQhv91Om49zz2BZcllieXPIUZZuHc',
    appId: '1:860783457646:web:f76cc56d498665f136bd7f',
    messagingSenderId: '860783457646',
    projectId: 'pls-app-server',
    authDomain: 'pls-app-server.firebaseapp.com',
    storageBucket: 'pls-app-server.appspot.com',
  );
}
